### ISSUE TITLE
 https://hub.docker.com/r/dko0/squoosh的镜像无法拉取了

### ISSUE THREAD

**Issue by petercham** [hellodk34/squoosh#1]
RT

**Comment by hellodk34** [comment]
确认下是不是需要 login。

另外现在 docker hub 在你的地区可能受到了 dns 污染，我帮你找一个镜像。

```
docker pull mirror.ccs.tencentyun.com/dko0/squoosh:1.12.0
```

直接拉下来就好。完成之后启动容器时，执行的镜像需要是 `mirror.ccs.tencentyun.com/dko0/squoosh:1.12.0` (需要写完整）

以下是我测试拉取的日志

```
# docker pull mirror.ccs.tencentyun.com/dko0/squoosh:1.12.0
1.12.0: Pulling from dko0/squoosh
Digest: sha256:582cceee7385a45c6d3d5d84459b6bc8adc2773c0b33fef5c623db5b0b76dfff
Status: Downloaded newer image for mirror.ccs.tencentyun.com/dko0/squoosh:1.12.0
mirror.ccs.tencentyun.com/dko0/squoosh:1.12.0
```

**Comment by hellodk34** [comment]
上一条评论说的腾讯云的镜像地址 `mirror.ccs.tencentyun.com` 是个内网域名，如果你不是腾讯云的机器是无法拉取的。

换一个镜像，换成阿里的或者网易的，又或者南京大学的： `docker pull docker.nju.edu.cn/dko0/squoosh:1.12.0`

**Comment by petercham** [comment]
非常感谢大佬的回复，有腾讯云镜像解决了大问题
