### ISSUE TITLE
updates failed

### ISSUE THREAD

**Issue by imdp6** [hellodk34/squoosh#2]
WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

**Comment by hellodk34** [comment]
请提供更加详细一点的日志。另外这是什么场景下的日志？

**Comment by imdp6** [comment]
> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-9cb42d0c.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-10T07_46_31_032Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-090904db.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-10T12_00_59_650Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-c020f7ec.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-10T12_02_43_139Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-50222992.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-12T07_28_13_109Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-7da6b6e8.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-12T22_07_29_563Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-eb51628c.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-13T00_49_26_403Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080
npm ERR! path /app/squoosh
npm ERR! command failed
npm ERR! signal SIGTERM
npm ERR! command sh /tmp/serve-14e435fa.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-07-13T01_01_27_158Z-debug-0.log

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

> squoosh@2.0.0 serve
> serve --listen=8080 --config ./serve.json ./build

WARNING: Checking for updates failed (use `--debug` to see full error)
INFO: Accepting connections at http://localhost:8080

**Comment by imdp6** [comment]
docker启动的时候就出现这个日志了

**Comment by hellodk34** [comment]
你这个是 `squoosh@2.0.0 serve` ？

我做的 docker 镜像最高只支持 `1.12.0`
