### ISSUE TITLE
大佬，是否能做一个cli的版本？

### ISSUE THREAD

**Issue by petercham** [hellodk34/squoosh#3]
RT

**Comment by hellodk34** [comment]
看看这个呢  `https://www.npmjs.com/package/@squoosh/cli`

**Comment by hellodk34** [comment]
针对 cli 的版本，我写了一篇文章，能保证你能轻松使用 squoosh-cli 批量压缩图片，请阅读下面这篇文章

[可能是]最好的压缩图片程序，使用 squoosh-cli 批量压缩图片 https://hellodk.cn/post/1141
